package com.kuaikan.comic.dao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMIC_BRIEF.
 */
public class ComicBriefBean {

    private Long id;
    private String cover_image_url;
    private Long created_at;
    private String title;
    private Long topic_id;
    private Long updated_at;
    private String url;

    public ComicBriefBean() {
    }

    public ComicBriefBean(Long id) {
        this.id = id;
    }

    public ComicBriefBean(Long id, String cover_image_url, Long created_at, String title, Long topic_id, Long updated_at, String url) {
        this.id = id;
        this.cover_image_url = cover_image_url;
        this.created_at = created_at;
        this.title = title;
        this.topic_id = topic_id;
        this.updated_at = updated_at;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCover_image_url() {
        return cover_image_url;
    }

    public void setCover_image_url(String cover_image_url) {
        this.cover_image_url = cover_image_url;
    }

    public Long getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Long created_at) {
        this.created_at = created_at;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getTopic_id() {
        return topic_id;
    }

    public void setTopic_id(Long topic_id) {
        this.topic_id = topic_id;
    }

    public Long getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Long updated_at) {
        this.updated_at = updated_at;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
